name: Update Demo Site

on: 
  workflow_dispatch:
  push: 
    branches:
      - master

jobs:
  trigger-github-action:
    runs-on: ubuntu-latest
    steps:
    - name: Triger Update Theme Action
      env:
        USER: ${{ github.actor }}
        REPO: itheme-demo-site
        EVENT_TYPE: UpdateTheme
      run: |
        curl -X POST https://api.github.com/repos/$USER/$REPO/dispatches  -H "Accept: application/vnd.github.everest-preview+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN}}"  --data '{"event_type": "$EVENT_TYPE"}'
